### ISSUE TITLE
Add View Job & View Job Results Endpoints

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-ios#11]
Add support for [View Job Details](https://m2x.att.com/developer/documentation/v2/jobs#View-Job-Details) / [View Job Results](https://m2x.att.com/developer/documentation/v2/jobs#View-Job-Results) endpoints from the [Jobs API](https://m2x.att.com/developer/documentation/v2/jobs)

**Comment by attsdk** [comment]
Implemented in #29.
