### ISSUE TITLE
Add Post Device Update (Single Values to Multiple Streams)

### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-ios#13]
Add [Post Device Update (Single Values to Multiple Streams)](https://m2x.att.com/developer/documentation/v2/device#Post-Device-Update--Single-Values-to-Multiple-Streams-) endpoint to the following client libraries, method should be named `postDeviceUpdate`

**Comment by attsdk** [comment]
PR Merged. Closing this issue.
